defaults:
  - mimicgen_image
  - _self_

name: Coffee_Preparation_T0

# Paper: Coffee_Preparation_T0
moe:
  num_experts: 16
  top_k: 4
  aux_loss_weight: 0.1
  lambda_balance: 1.0
  lambda_entropy: 0.1
